### ISSUE TITLE
feature request:windows support

### ISSUE THREAD

**Issue by Ecalose** [blacknon/lssh#86]
could you support windows?i tried to build the binary in the windows but failed.I might build in a wrong way?

CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build ./cmd/lssh

**Comment by blacknon** [comment]
Probably because the pkcs11 library you are using is calling C, you will not be able to cross-compile.
If you compile it on Windows, it will work, but it is not recommended because the terminal display is distorted.
Also, since lsftp currently uses some UNIX-like syscalls, I think it will fail to compile.

I would like to support Windows in the future, but I haven't done it yet.

**Comment by Ecalose** [comment]
> Probably because the pkcs11 library you are using is calling C, you will not be able to cross-compile. If you compile it on Windows, it will work, but it is not recommended because the terminal display is distorted. Also, since lsftp currently uses some UNIX-like syscalls, I think it will fail to compile.
> 
> I would like to support Windows in the future, but I haven't done it yet.

oh,thx
